apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "{{ AUTHZPOLICY_CRD_NAME }}"
  namespace: {{ NAMESPACE }}
spec:
  selector:
    matchLabels:
      {{ RULE_MATCH_KEY_VALUE }}
  action: {{ ACTION }}
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
